version: "3.4"

services:
  tomcat:
    env_file:
      - .env
    build:
      context: ../../
      dockerfile: docker/DockerfileTomcatTest
    volumes: 
        - ./:/code
    ports:
      - "1010:8080"
