version: "3.4"

services:
  tomcat:
    env_file:
      - .env
    args:
      - COLLECTOR:${PROJECT}
    build:
      context: ../../
      dockerfile: docker/DockerfileTomcatTest
    ports:
      - "1010:8080"
