version: "3.4"

services:
  tomcat:
    env_file:
      - .env
    build:
      context: ../../
      dockerfile: docker/DockerfileTomcatTest
      args:
        - COLLECTOR=${PROJECT}
    ports:
      - "1011:8080"
