version: "3.4"

services:
  app:
    image: maven:3-jdk-8-alpine
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    volumes:
      - ./:/code
      - ~/.m2/:/var/maven/.m2
    working_dir: /code
    command: mvn -Duser.home=/var/maven test



