name: CI environment-appa-bz-tenminutes

on:
  push:
    paths:
      - "data-collectors/airquality-appabz/**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: cd data-collectors/environment-appa-bz-tenminutes && mvn -B -U clean compile test

  
